nginx:
    image: nginx:1.29-alpine
    container_name: nginx
    env_file: .env
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template
    ports:
      - "8080:80"
    depends_on:
      - app_blue
      - app_green

  app_blue:
    image: yimikaade/wonderful:devops-stage-two
    container_name: app_blue
    environment:
      - APP_POOL=blue
      - RELEASE_ID=v1.0.0
    ports:
      - "8081:3000"

  app_green:
    image: yimikaade/wonderful:devops-stage-two
    container_name: app_green
    environment:
      - APP_POOL=green
      - RELEASE_ID=v2.0.0
    ports:
      - "8082:3000"


   
